import Database from "better-sqlite3";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { chunkPdfPages, chunkTranscript, chunkTranscriptForAnalysis, mergeStudyNotes, normalizeProviderError, sha256, validateWeekStudyNotes } from "../electron/ai/core";
import { runMigrations } from "../electron/database/migrations";
import { LectureMateService } from "../electron/services/lectureMateService";
import type { WeekStudyNotes } from "../shared/domain";
import { isInvalidTranslation, parseStructuredJson } from "../electron/ai/provider";
import { backfillEmptyStudyNoteSections, ensureMapEvidence, mapWithConcurrency, mergeMapAnalyses, restoreStudyNoteEvidence, scoreTeacherEmphasis, validateMapAnalysis } from "../electron/ai/pipeline";

const empty = (weekId = "w"): WeekStudyNotes => ({ weekId, coreConcepts: [], teacherEmphasis: [], lectureAdditions: [], confusingConcepts: [], examples: [], assessmentInfo: [], formulasAndDefinitions: [], reviewPriorities: [], finalSummary: "summary" });

describe("Phase 4 AI core", () => {
  let db: Database.Database; let root: string; let service: LectureMateService; let weekId: string;
  beforeEach(() => { root = join(tmpdir(), `lecturemate-ai-${randomUUID()}`); mkdirSync(join(root, "courses"), { recursive: true }); db = new Database(":memory:"); db.pragma("foreign_keys = ON"); runMigrations(db); service = new LectureMateService(db, join(root, "courses"), root); const course = service.createCourse({ code: "AI", name: "AI", color: "#5b6ee1", icon: "BookOpen" }); weekId = service.createWeek(course.id).id; });
  afterEach(() => { db.close(); rmSync(root, { recursive: true, force: true }); });

  it("按句子边界切分字幕并生成稳定 source hash", () => { const chunks = chunkTranscript("w", "First sentence. Second sentence.\n\nThird paragraph.", 28); expect(chunks.length).toBeGreaterThan(1); expect(chunks.map((c) => c.orderIndex)).toEqual(chunks.map((_, i) => i)); expect(chunks[0].sourceHash).toBe(sha256(chunks[0].sourceText)); });
  it("学习笔记分析会合并多个句子以减少 API 请求", () => { const text = Array.from({ length: 20 }, (_, i) => `Sentence number ${i}.`).join(" "); expect(chunkTranscriptForAnalysis("w", text, 120).length).toBeLessThan(chunkTranscript("w", text, 120).length); });
  it("保留 PDF 页码且只在页面间分组", () => { const chunks = chunkPdfPages([{ pageNumber: 2, text: "a".repeat(5) }, { pageNumber: 3, text: "b".repeat(5) }], 6); expect(chunks).toHaveLength(2); expect(chunks[1][0].pageNumber).toBe(3); });
  it("校验并归一化结构化内容和 Evidence", () => { const value = empty(); value.coreConcepts = [{ title: "OFDM", summary: "概念", evidence: [{ source: "pdf", pageNumber: 7, text: "OFDM" }] }]; expect(validateWeekStudyNotes(value, "week").coreConcepts[0].evidence[0].pageNumber).toBe(7); const normalized = validateWeekStudyNotes({ ...value, coreConcepts: [{ title: "x", summary: "y", evidence: [{ pageNumber: 3, quote: "quoted" }] }] }, "week"); expect(normalized.coreConcepts[0].evidence[0]).toMatchObject({ source: "pdf", pageNumber: 3, text: "quoted" }); expect(() => validateWeekStudyNotes({ ...value, coreConcepts: [{ title: "x", summary: "y", evidence: [{}] }] }, "week")).toThrow("依据"); });
  it("Map/Reduce 合并时去重但保留不同知识点", () => { const a = empty(); a.coreConcepts = [{ title: "SNR", summary: "ratio", evidence: [{ source: "pdf", text: "SNR" }] }]; const merged = mergeStudyNotes("w", [a, a, { coreConcepts: [{ title: "BER", summary: "rate", evidence: [{ source: "transcript", text: "BER" }] }] }]); expect(merged.coreConcepts.map((x) => x.title)).toEqual(["SNR", "BER"]); });
  it("翻译缓存只接受当前 TXT source hash，并保留部分成功块", () => { const source = join(root, "t.txt"); writeFileSync(source, "First sentence. Second sentence."); service.importFile(weekId, "transcript_txt", source); const chunk = chunkTranscript(weekId, "First sentence. Second sentence.")[0]; const now = new Date().toISOString(); service.ai.saveTranslation({ ...chunk, translatedText: "第一句。第二句。", provider: "openrouter", model: "free", createdAt: now, updatedAt: now }); expect(service.getTranslationStatus(weekId).chunks).toHaveLength(1); writeFileSync(source, "Changed transcript."); service.importFile(weekId, "transcript_txt", source); const status = service.getTranslationStatus(weekId); expect(status.chunks).toHaveLength(0); expect(status.stale).toBe(true); });
  it("AI 笔记 generatedContent 与 editedContent 分开持久化", () => { const now = new Date().toISOString(); service.ai.saveStudyNotes({ id: randomUUID(), weekId, provider: "openrouter", model: "free", sourceHash: "hash", status: "complete", generatedContent: empty(weekId), editedContent: null, createdAt: now, updatedAt: now }); const edited = { ...empty(weekId), finalSummary: "我的编辑" }; service.saveEditedStudyNotes(weekId, edited); const saved = service.getStudyNotes(weekId)!; expect(saved.generatedContent.finalSummary).toBe("summary"); expect(saved.editedContent?.finalSummary).toBe("我的编辑"); });
  it("只在用户确认操作后删除已持久化的 AI 笔记", () => { const now = new Date().toISOString(); service.ai.saveStudyNotes({ id: randomUUID(), weekId, provider: "openrouter", model: "free", sourceHash: "hash", status: "complete", generatedContent: empty(weekId), editedContent: null, createdAt: now, updatedAt: now }); expect(service.getStudyNotes(weekId)).not.toBeNull(); service.deleteStudyNotes(weekId); expect(service.getStudyNotes(weekId)).toBeNull(); });
  it("归一化 Provider 错误且隐藏 API Key", () => { expect(normalizeProviderError(new Error("401 invalid api key sk-secret123")).message).toBe("API Key 无效或未获授权"); expect(normalizeProviderError(new Error("429 rate limit")).message).toContain("请求过于频繁"); });
  it("兼容 Markdown 和解释文字包裹的 AI JSON", () => { expect(parseStructuredJson<{ ok: boolean }>("结果如下：\n```json\n{\"ok\":true}\n```\n完成")).toEqual({ ok: true }); expect(parseStructuredJson<{ text: string }>('prefix {"text":"brace } inside"} suffix').text).toBe("brace } inside"); });
  it("拒绝把安全分类元数据当作字幕译文",()=>{expect(isInvalidTranslation("User Safety: safe")).toBe(true);expect(isInvalidTranslation("Safety assessment: blocked.")).toBe(true);expect(isInvalidTranslation("用户可以安全地操作设备。")).toBe(false);});
  it("Map 阶段有限并发且保持结果顺序", async () => { let active = 0; let peak = 0; const result = await mapWithConcurrency([1,2,3,4,5,6], 3, async (value) => { active++; peak = Math.max(peak, active); await new Promise((resolve) => setTimeout(resolve, 3)); active--; return value * 2; }); expect(peak).toBe(3); expect(result).toEqual([2,4,6,8,10,12]); });
  it("有限并发队列支持取消且不继续领取新任务", async () => { let cancelled = false; let started = 0; await expect(mapWithConcurrency([1,2,3,4,5], 2, async (value) => { started++; if (value === 1) cancelled = true; return value; }, () => cancelled)).rejects.toMatchObject({ name: "AbortError" }); expect(started).toBeLessThanOrEqual(2); });
  it("Map schema 校验、去重和 SQLite sourceHash cache 可复用", () => { const raw = { concepts: [{ title: "OFDM", summary: "multi-carrier", evidence: [{ source: "pdf", pageNumber: 2, text: "OFDM" }] }], teacherEmphasis: [], lectureAdditions: [], assessmentInfo: [], formulas: [] }; const value = validateMapAnalysis(raw); expect(mergeMapAnalyses([value, value]).concepts).toHaveLength(1); service.ai.saveMapResult({ id: randomUUID(), weekId, stage: "pdf", orderIndex: 0, sourceHash: "source", provider: "openrouter", model: "free", result: value, durationMs: 12 }); expect(service.ai.getMapResult(weekId, "pdf", "source", "openrouter", "free")).toEqual(value); expect(service.ai.getMapResult(weekId, "pdf", "changed", "openrouter", "free")).toBeNull(); });
  it("支持同一 Week 的 Lecture CRUD、排序和独立字幕缓存", () => { const one=service.createLectureSession(weekId); const two=service.createLectureSession(weekId); expect(service.listLectureSessions(weekId).map(v=>v.title)).toEqual(["Lecture 1","Lecture 2"]); service.updateLectureSession(two.id,"Tutorial"); service.moveLectureSession(two.id,"up"); expect(service.listLectureSessions(weekId).map(v=>v.title)).toEqual(["Tutorial","Lecture 1"]); const a=join(root,"a.txt"),b=join(root,"b.txt");writeFileSync(a,"Same sentence.");writeFileSync(b,"Same sentence.");service.importLectureAsset(one.id,"transcript_txt",a);service.importLectureAsset(two.id,"transcript_txt",b);const c1=service.getTranslationStatus(one.id).sourceChunks[0],c2=service.getTranslationStatus(two.id).sourceChunks[0];expect(c1.sourceHash).toBe(c2.sourceHash);expect(c1.lectureSessionId).not.toBe(c2.lectureSessionId);const now=new Date().toISOString();service.ai.saveTranslation({...c1,translatedText:"句子。",provider:"openrouter",model:"free",createdAt:now,updatedAt:now});expect(service.getTranslationStatus(one.id).chunks).toHaveLength(1);expect(service.getTranslationStatus(two.id).chunks).toHaveLength(0);service.deleteLectureSession(two.id);expect(service.listLectureSessions(weekId)).toHaveLength(1); });
  it("公式 Map 保留表达式、变量、页码和低置信度并按表达式去重",()=>{const raw={concepts:[],teacherEmphasis:[],lectureAdditions:[],assessmentInfo:[],formulas:[{name:"Shannon capacity",expression:"C = B log2(1+SNR)",meaning:"channel capacity",variables:["C","B","SNR"],pageNumber:19,context:"OCR partly damaged",confidence:.35}]};const formula=validateMapAnalysis(raw,"pdf").formulas[0];expect(formula).toMatchObject({title:"Shannon capacity",expression:"C = B log2(1+SNR)",variables:["C","B","SNR"],confidence:.35});expect(formula.evidence[0].pageNumber).toBe(19);expect(mergeMapAnalyses([validateMapAnalysis(raw,"pdf"),validateMapAnalysis(raw,"pdf")]).formulas).toHaveLength(1);});
  it("模型遗漏依据时从 Map 源块补齐，并在 Reduce 丢失后恢复",()=>{const raw={concepts:[{title:"OFDM",summary:"multicarrier",evidence:[]}],teacherEmphasis:[],lectureAdditions:[],assessmentInfo:[],formulas:[]};const mapped=ensureMapEvidence(validateMapAnalysis(raw,"pdf"),{stage:"pdf",sourceText:"[PDF page 7]\nOFDM uses orthogonal subcarriers."});expect(mapped.concepts[0].evidence[0]).toMatchObject({source:"pdf",pageNumber:7});const notes=empty();notes.coreConcepts=[{title:"OFDM",summary:"正交多载波",evidence:[]}];expect(restoreStudyNoteEvidence(notes,mapped).coreConcepts[0].evidence).toHaveLength(1);});
  it("老师重点评分只使用 Transcript 信号，明确强调、重复与跨 Lecture 会提高分数",()=>{const make=(explicitEmphasis:number,repeatedMentions:number,lectureIds:string[])=>({title:"OFDM",summary:"x",evidence:lectureIds.map(lectureSessionId=>({source:"transcript" as const,text:"important OFDM",lectureSessionId})),teacherSignals:{explicitEmphasis,repeatedMentions,explanationDepth:2,examples:[],comparisons:[],warnings:[],assessmentMentions:[]}});expect(scoreTeacherEmphasis(make(2,2,["l1","l2"])).importance).toBeGreaterThan(scoreTeacherEmphasis(make(0,0,["l1"])).importance);});
  it("PDF Map 不会产生 Teacher signal，Transcript Map 会保存 assessment 与讲解特征",()=>{const raw={concepts:[],teacherEmphasis:[{concept:"OFDM",explanationSummary:"重点",explicitEmphasis:2,repeatedMentions:2,explanationDepth:3,examples:["WiFi"],comparisons:[],warnings:["don't confuse"],assessmentMentions:["quiz"],transcriptEvidence:["important"]}],lectureAdditions:[],assessmentInfo:[],formulas:[]};expect(validateMapAnalysis(raw,"pdf").teacherEmphasis[0].teacherSignals).toBeUndefined();expect(validateMapAnalysis(raw,"transcript").teacherEmphasis[0].teacherSignals?.assessmentMentions).toEqual(["quiz"]);});
  it("多 Lecture 老师重点按 concept 合并并累积证据",()=>{const raw=(lectureSessionId:string)=>ensureMapEvidence(validateMapAnalysis({concepts:[],teacherEmphasis:[{concept:"OFDM",summary:"x",explicitEmphasis:1,repeatedMentions:1,evidence:["important"]}],lectureAdditions:[],assessmentInfo:[],formulas:[]}),{stage:"transcript",sourceText:"important OFDM",lectureSessionId,lectureTitle:lectureSessionId});const merged=mergeMapAnalyses([raw("l1"),raw("l2")]);expect(merged.teacherEmphasis).toHaveLength(1);expect(new Set(merged.teacherEmphasis[0].evidence.map(e=>e.lectureSessionId)).size).toBe(2);});
  it("后台 Job 防止重复启动，并在没有页面订阅时仍保存失败状态和通知",async()=>{const events:string[]=[];const pages=[{pageNumber:1,text:"OFDM"}];const first=service.startStudyNotesJob(weekId,pages,false,job=>events.push(job.status));const duplicate=service.startStudyNotesJob(weekId,pages);expect(duplicate.id).toBe(first.id);await new Promise(resolve=>setTimeout(resolve,0));const saved=service.listAIAnalysisJobs()[0];expect(saved.status).toBe("failed");expect(saved.error).toContain("API Key");expect(events).toContain("failed");});
  it("Reduce 返回空栏目时从已验证 Map 事实回填，不保存全 0 笔记",()=>{const mapped=validateMapAnalysis({concepts:[{title:"OFDM",summary:"multicarrier",evidence:[{source:"pdf",text:"OFDM"}]}],teacherEmphasis:[{title:"Fading",summary:"important",explicitEmphasis:2,evidence:[{source:"transcript",text:"This is important"}]}],lectureAdditions:[],assessmentInfo:[],formulas:[]},"transcript");const result=backfillEmptyStudyNoteSections(empty(),mapped);expect(result.coreConcepts).toHaveLength(1);expect(result.teacherEmphasis).toHaveLength(1);expect(result.reviewPriorities.length).toBeGreaterThan(0);});
});
