import { contextBridge, ipcRenderer } from "electron";
import type { LectureMateApi } from "../shared/contracts";
import { CHANNELS } from "./ipc";

const api: LectureMateApi = {
  getCourseTree: () => ipcRenderer.invoke(CHANNELS.tree),
  createCourse: (input) => ipcRenderer.invoke(CHANNELS.createCourse, input),
  updateCourse: (input) => ipcRenderer.invoke(CHANNELS.updateCourse, input),
  deleteCourse: (id) => ipcRenderer.invoke(CHANNELS.deleteCourse, id),
  createWeek: (input) => ipcRenderer.invoke(CHANNELS.createWeek, input),
  updateWeek: (input) => ipcRenderer.invoke(CHANNELS.updateWeek, input),
  deleteWeek: (id) => ipcRenderer.invoke(CHANNELS.deleteWeek, id),
  importWeekFile: (input) => ipcRenderer.invoke(CHANNELS.importFile, input),
  getSettings: () => ipcRenderer.invoke(CHANNELS.getSettings),
  updateSettings: (input) => ipcRenderer.invoke(CHANNELS.updateSettings, input),
  getDataDirectory: () => ipcRenderer.invoke(CHANNELS.dataDirectory),
  getReaderMaterials: (weekId) => ipcRenderer.invoke(CHANNELS.readerMaterials, weekId),
  listLectureSessions:(weekId)=>ipcRenderer.invoke(CHANNELS.lectures,weekId),
  createLectureSession:(input)=>ipcRenderer.invoke(CHANNELS.createLecture,input),
  updateLectureSession:(input)=>ipcRenderer.invoke(CHANNELS.updateLecture,input),
  moveLectureSession:(input)=>ipcRenderer.invoke(CHANNELS.moveLecture,input),
  deleteLectureSession:(id)=>ipcRenderer.invoke(CHANNELS.deleteLecture,id),
  importLectureAsset:(input)=>ipcRenderer.invoke(CHANNELS.importLectureAsset,input),
  getLectureMaterials:(id)=>ipcRenderer.invoke(CHANNELS.lectureMaterials,id),
  updateReadingProgress: (input) => ipcRenderer.invoke(CHANNELS.readingProgress, input),
  listAnnotations: (weekId, pageNumber) => ipcRenderer.invoke(CHANNELS.annotations, weekId, pageNumber),
  saveAnnotation: (annotation) => ipcRenderer.invoke(CHANNELS.saveAnnotation, annotation),
  deleteAnnotation: (id) => ipcRenderer.invoke(CHANNELS.deleteAnnotation, id),
  listNotes: (weekId) => ipcRenderer.invoke(CHANNELS.notes, weekId),
  saveNote: (input) => ipcRenderer.invoke(CHANNELS.saveNote, input),
  deleteNote: (id) => ipcRenderer.invoke(CHANNELS.deleteNote, id),
  getAISettings: () => ipcRenderer.invoke(CHANNELS.aiSettings),
  updateAISettings: (input) => ipcRenderer.invoke(CHANNELS.updateAISettings, input),
  testAIConnection: (input) => ipcRenderer.invoke(CHANNELS.testAI, input),
  getTranslationStatus: (weekId) => ipcRenderer.invoke(CHANNELS.translationStatus, weekId),
  translateTranscriptChunk: (input) => ipcRenderer.invoke(CHANNELS.translateChunk, input),
  getStudyNotes: (weekId) => ipcRenderer.invoke(CHANNELS.studyNotes, weekId),
  generateStudyNotes: (input) => ipcRenderer.invoke(CHANNELS.generateStudyNotes, input),
  startStudyNotesJob: (input) => ipcRenderer.invoke(CHANNELS.startAIJob, input),
  listAIAnalysisJobs: () => ipcRenderer.invoke(CHANNELS.aiJobs),
  onAIAnalysisJob: (listener) => { const handler = (_event: Electron.IpcRendererEvent, job: Parameters<typeof listener>[0]) => listener(job); ipcRenderer.on(CHANNELS.aiJob, handler); return () => ipcRenderer.removeListener(CHANNELS.aiJob, handler); },
  onAIAnalysisProgress: (listener) => { const handler = (_event: Electron.IpcRendererEvent, progress: Parameters<typeof listener>[0]) => listener(progress); ipcRenderer.on(CHANNELS.aiProgress, handler); return () => ipcRenderer.removeListener(CHANNELS.aiProgress, handler); },
  cancelStudyNotes: (weekId) => ipcRenderer.invoke(CHANNELS.cancelStudyNotes, weekId),
  saveEditedStudyNotes: (weekId, content) => ipcRenderer.invoke(CHANNELS.editStudyNotes, weekId, content),
  deleteStudyNotes: (weekId) => ipcRenderer.invoke(CHANNELS.deleteStudyNotes, weekId),
};
contextBridge.exposeInMainWorld("lectureMate", api);
