import type Database from "better-sqlite3";
import type { StoredWeekStudyNotes, TranscriptTranslationChunk, WeekStudyNotes } from "../../shared/domain";

export class AIRepository {
  constructor(private readonly db: Database.Database) {}
  getEncryptedKey(): string | null { return (this.db.prepare("SELECT encrypted_api_key FROM ai_provider_settings WHERE provider='openrouter'").get() as { encrypted_api_key: string | null } | undefined)?.encrypted_api_key ?? null; }
  setEncryptedKey(value: string): void { this.db.prepare(`INSERT INTO ai_provider_settings(provider,encrypted_api_key,updated_at) VALUES('openrouter',?,?) ON CONFLICT(provider) DO UPDATE SET encrypted_api_key=excluded.encrypted_api_key,updated_at=excluded.updated_at`).run(value, new Date().toISOString()); }
  listTranslations(lectureSessionId: string): TranscriptTranslationChunk[] { return this.db.prepare("SELECT id,week_id weekId,lecture_session_id lectureSessionId,order_index orderIndex,source_text sourceText,source_hash sourceHash,translated_text translatedText,provider,model,created_at createdAt,updated_at updatedAt FROM transcript_translation_chunks WHERE lecture_session_id=? ORDER BY order_index").all(lectureSessionId) as TranscriptTranslationChunk[]; }
  deleteTranslation(id:string):void{this.db.prepare("DELETE FROM transcript_translation_chunks WHERE id=?").run(id);}
  saveTranslation(value: TranscriptTranslationChunk): TranscriptTranslationChunk { const exists=this.db.prepare("SELECT 1 FROM lecture_sessions WHERE id=?").get(value.lectureSessionId); const fallback=!exists?this.db.prepare("SELECT id,title FROM lecture_sessions WHERE week_id=? ORDER BY order_index LIMIT 1").get(value.weekId) as {id:string;title:string}|undefined:undefined; const resolved=fallback?{...value,lectureSessionId:fallback.id,lectureTitle:fallback.title}:value; this.db.prepare(`INSERT INTO transcript_translation_chunks(id,week_id,lecture_session_id,order_index,source_text,source_hash,translated_text,provider,model,created_at,updated_at) VALUES(@id,@weekId,@lectureSessionId,@orderIndex,@sourceText,@sourceHash,@translatedText,@provider,@model,@createdAt,@updatedAt) ON CONFLICT(lecture_session_id,order_index,source_hash) DO UPDATE SET translated_text=excluded.translated_text,provider=excluded.provider,model=excluded.model,updated_at=excluded.updated_at`).run(resolved); return resolved; }
  getStudyNotes(weekId: string): StoredWeekStudyNotes | null { const row = this.db.prepare("SELECT id,week_id weekId,provider,model,source_hash sourceHash,status,generated_content_json generated,edited_content_json edited,created_at createdAt,updated_at updatedAt FROM ai_study_notes WHERE week_id=?").get(weekId) as Record<string,string|null> | undefined; if (!row) return null; return { id: row.id!, weekId: row.weekId!, provider: row.provider!, model: row.model!, sourceHash: row.sourceHash!, status: row.status as StoredWeekStudyNotes["status"], generatedContent: JSON.parse(row.generated!) as WeekStudyNotes, editedContent: row.edited ? JSON.parse(row.edited) as WeekStudyNotes : null, createdAt: row.createdAt!, updatedAt: row.updatedAt! }; }
  saveStudyNotes(value: StoredWeekStudyNotes): StoredWeekStudyNotes { this.db.prepare(`INSERT INTO ai_study_notes(id,week_id,provider,model,source_hash,status,generated_content_json,edited_content_json,created_at,updated_at) VALUES(@id,@weekId,@provider,@model,@sourceHash,@status,@generated,@edited,@createdAt,@updatedAt) ON CONFLICT(week_id) DO UPDATE SET provider=excluded.provider,model=excluded.model,source_hash=excluded.source_hash,status=excluded.status,generated_content_json=excluded.generated_content_json,edited_content_json=excluded.edited_content_json,updated_at=excluded.updated_at`).run({ ...value, generated: JSON.stringify(value.generatedContent), edited: value.editedContent ? JSON.stringify(value.editedContent) : null }); return value; }
  deleteStudyNotes(weekId: string): boolean { return this.db.prepare("DELETE FROM ai_study_notes WHERE week_id=?").run(weekId).changes > 0; }
  getMapResult(weekId: string, stage: "pdf" | "transcript", sourceHash: string, provider: string, model: string): unknown | null { const row = this.db.prepare("SELECT result_json FROM ai_map_cache WHERE week_id=? AND stage=? AND source_hash=? AND provider=? AND model=?").get(weekId, stage, sourceHash, provider, model) as { result_json: string } | undefined; if (!row) return null; try { return JSON.parse(row.result_json) as unknown; } catch { return null; } }
  listMapResults(weekId:string):{stage:"pdf"|"transcript";result:unknown;lectureSessionId?:string;lectureTitle?:string}[]{return (this.db.prepare("SELECT stage,result_json,lecture_session_id,lecture_title FROM ai_map_cache WHERE week_id=? ORDER BY stage,order_index").all(weekId) as {stage:"pdf"|"transcript";result_json:string;lecture_session_id:string|null;lecture_title:string|null}[]).flatMap(row=>{try{return [{stage:row.stage,result:JSON.parse(row.result_json) as unknown,...(row.lecture_session_id?{lectureSessionId:row.lecture_session_id}:{ }),...(row.lecture_title?{lectureTitle:row.lecture_title}:{ })}];}catch{return [];}});}
  saveMapResult(input: { id: string; weekId: string; stage: "pdf" | "transcript"; orderIndex: number; sourceHash: string; provider: string; model: string; result: unknown; durationMs: number; lectureSessionId?: string; lectureTitle?: string }): void { const now = new Date().toISOString(); this.db.prepare(`INSERT INTO ai_map_cache(id,week_id,stage,order_index,source_hash,provider,model,result_json,duration_ms,created_at,updated_at,lecture_session_id,lecture_title) VALUES(@id,@weekId,@stage,@orderIndex,@sourceHash,@provider,@model,@resultJson,@durationMs,@now,@now,@lectureSessionId,@lectureTitle) ON CONFLICT(week_id,stage,source_hash,provider,model) DO UPDATE SET result_json=excluded.result_json,duration_ms=excluded.duration_ms,updated_at=excluded.updated_at,lecture_session_id=excluded.lecture_session_id,lecture_title=excluded.lecture_title`).run({ lectureSessionId:null, lectureTitle:null, ...input, resultJson: JSON.stringify(input.result), now }); }
  countMapResults(weekId: string): number { return (this.db.prepare("SELECT COUNT(*) count FROM ai_map_cache WHERE week_id=?").get(weekId) as { count: number }).count; }
  clearMapResults(weekId: string): void { this.db.prepare("DELETE FROM ai_map_cache WHERE week_id=?").run(weekId); }
}
