import type Database from "better-sqlite3";
import type { LectureAsset, LectureAssetKind, LectureSession } from "../../shared/domain";

interface AssetRow { id: string; week_id: string; kind: LectureAssetKind; original_name: string; managed_path: string; sha256: string; size_bytes: number; created_at: string; updated_at: string }
interface SessionRow { id: string; week_id: string; title: string; order_index: number; transcript_txt_asset_id: string | null; timestamp_json_asset_id: string | null; created_at: string; updated_at: string }
const asset = (r: AssetRow): LectureAsset => ({ id:r.id, weekId:r.week_id, kind:r.kind, originalName:r.original_name, managedPath:r.managed_path, sha256:r.sha256, sizeBytes:r.size_bytes, createdAt:r.created_at, updatedAt:r.updated_at });

export class LectureRepository {
  constructor(private readonly db: Database.Database) {}
  private map(r: SessionRow): LectureSession { const assets = this.listAssets(r.week_id); return { id:r.id, weekId:r.week_id, title:r.title, orderIndex:r.order_index, transcriptTxtAssetId:r.transcript_txt_asset_id, timestampJsonAssetId:r.timestamp_json_asset_id, transcriptAsset:assets.find(a=>a.id===r.transcript_txt_asset_id) ?? null, timestampAsset:assets.find(a=>a.id===r.timestamp_json_asset_id) ?? null, createdAt:r.created_at, updatedAt:r.updated_at }; }
  list(weekId: string): LectureSession[] { return (this.db.prepare("SELECT * FROM lecture_sessions WHERE week_id=? ORDER BY order_index").all(weekId) as SessionRow[]).map(r=>this.map(r)); }
  find(id: string): LectureSession | undefined { const row=this.db.prepare("SELECT * FROM lecture_sessions WHERE id=?").get(id) as SessionRow|undefined; return row ? this.map(row) : undefined; }
  listAssets(weekId: string): LectureAsset[] { return (this.db.prepare("SELECT * FROM lecture_assets WHERE week_id=?").all(weekId) as AssetRow[]).map(asset); }
  create(id:string,weekId:string,title:string,orderIndex:number,now:string): LectureSession { this.db.prepare("INSERT INTO lecture_sessions(id,week_id,title,order_index,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(id,weekId,title,orderIndex,now,now); return this.find(id)!; }
  updateTitle(id:string,title:string,now:string): LectureSession|undefined { const changed=this.db.prepare("UPDATE lecture_sessions SET title=?,updated_at=? WHERE id=?").run(title,now,id).changes; return changed ? this.find(id) : undefined; }
  saveAsset(value:LectureAsset,sessionId:string): LectureAsset { const session=this.find(sessionId); if(!session) throw new Error("找不到该 Lecture"); const oldId=value.kind==="transcript_txt" ? session.transcriptTxtAssetId : session.timestampJsonAssetId; this.db.transaction(()=>{ this.db.prepare("INSERT INTO lecture_assets(id,week_id,kind,original_name,managed_path,sha256,size_bytes,created_at,updated_at) VALUES(@id,@weekId,@kind,@originalName,@managedPath,@sha256,@sizeBytes,@createdAt,@updatedAt)").run(value); const column=value.kind==="transcript_txt" ? "transcript_txt_asset_id" : "timestamp_json_asset_id"; this.db.prepare(`UPDATE lecture_sessions SET ${column}=?,updated_at=? WHERE id=?`).run(value.id,value.updatedAt,sessionId); if(oldId) this.db.prepare("DELETE FROM lecture_assets WHERE id=?").run(oldId); })(); return value; }
  move(id:string,direction:"up"|"down",now:string): LectureSession[] { const current=this.find(id); if(!current) throw new Error("找不到该 Lecture"); const target=this.db.prepare(`SELECT * FROM lecture_sessions WHERE week_id=? AND order_index ${direction==="up"?"<":">"} ? ORDER BY order_index ${direction==="up"?"DESC":"ASC"} LIMIT 1`).get(current.weekId,current.orderIndex) as SessionRow|undefined; if(!target) return this.list(current.weekId); this.db.transaction(()=>{ const temporary=(this.db.prepare("SELECT COALESCE(MAX(order_index),0)+1 value FROM lecture_sessions WHERE week_id=?").get(current.weekId) as {value:number}).value; this.db.prepare("UPDATE lecture_sessions SET order_index=? WHERE id=?").run(temporary,current.id); this.db.prepare("UPDATE lecture_sessions SET order_index=?,updated_at=? WHERE id=?").run(current.orderIndex,now,target.id); this.db.prepare("UPDATE lecture_sessions SET order_index=?,updated_at=? WHERE id=?").run(target.order_index,now,current.id); })(); return this.list(current.weekId); }
  delete(id:string): boolean { const current=this.find(id); if(!current) return false; this.db.transaction(()=>{ const assetIds=[current.transcriptTxtAssetId,current.timestampJsonAssetId].filter((value):value is string=>Boolean(value)); this.db.prepare("DELETE FROM lecture_sessions WHERE id=?").run(id); for(const assetId of assetIds)this.db.prepare("DELETE FROM lecture_assets WHERE id=?").run(assetId); const rows=this.db.prepare("SELECT id FROM lecture_sessions WHERE week_id=? ORDER BY order_index").all(current.weekId) as {id:string}[]; rows.forEach((r,i)=>this.db.prepare("UPDATE lecture_sessions SET order_index=? WHERE id=?").run(i+1,r.id)); })(); return true; }
}
